### ISSUE TITLE
May add another related work as reference

### ISSUE THREAD

**Issue by wjn1996** [nuochenpku/Graph-Reasoning-LLM#1]
Dear authors,

GraphWiz is a nice work. During reading your paper, I noticed that our research work [InstructGraph: Boosting Large Language Models via Graph-centric Instruction Tuning and Preference Alignment](https://arxiv.org/pdf/2402.08785.pdf) was released on 13th Feb, 2024, which is also focused on graph-centric instruction-tuning and preference alignment in graph reasoning and generation, and is highly relevant to your field of study.

I believe incorporating our work into your list of references will add depth to your study while also offering a more comprehensive graph learning with LLMs for scholars in the related fields. If you find it appropriate, I would greatly appreciate it if you could cite our paper.

Wishing you smooth progress in your research!

**Comment by nuochenpku** [comment]
Thank you for your suggestions. We are actually keeping a close eye on your work and find it very comprehensive. Coincidentally, our current work is in the review stage of KDD, and after incorporating the reviewers' comments, we will cite and discuss your work in our paper and update the existing version.
