### ISSUE TITLE
Question about GraphInstruct Dataset

### ISSUE THREAD

**Issue by hyworrywart** [nuochenpku/Graph-Reasoning-LLM#2]
Hi,

Thank you for your great work.

I've noticed the following issues with the QA pairs in GraphInstruct:

1. Some answers are only "Yes" or "No" without specific reasoning paths, especially in the flow and substructure datasets, as shown in Figure 1.
2. Some answers appear to be truncated, as shown in Figure 2.
3. Some answers seem to be incorrect, as shown in Figure 3.

![f2](https://github.com/nuochenpku/Graph-Reasoning-LLM/assets/136224080/d5f435a4-01fb-4b1c-bfac-8b327fa116b9)

![f1](https://github.com/nuochenpku/Graph-Reasoning-LLM/assets/136224080/3ea1fa95-bef6-49f8-bc2b-c6f47e44631e)

![f3](https://github.com/nuochenpku/Graph-Reasoning-LLM/assets/136224080/df68b30c-8a74-4cb0-b3fe-a991928990e3)

Will these issues impact the reasoning capabilities of LLMs? The results show that the model performs well on the flow and subgraph datasets.

Thanks!

**Comment by jerrynchen** [comment]
Hi, thanks for your interests in our work!

Our collection process are complex and generating paths are from LLMs, and then we use the regular expression to extract the answers. Thus, we can not directly control all paths' quality, resulting in some mistakes in current version.

 But, the above answers only account for a small part of all data. 
We use the above data version to train our current LLMs. Therefore, we believe it will have some impact on our model, but it will not affect the overall performance of the model.

At last, we have already noticed the above issues that current reasoning paths in training data generated by GPT-4 or augmented LLMs may be wrong (hallucination or truncated answers). We have now developed a considerable method to solve this problem, please look forward to our latest work.
